In [53]:
import pandas as pd

In [54]:
stu=pd.read_csv("/Users/sharoonkk/Documents/DA/ML/Student_Performance.csv")

In [55]:
stu

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [56]:
from sklearn.preprocessing import LabelEncoder

In [57]:
std=stu.select_dtypes("O")

In [58]:
std

Extracurricular Activities
0                           Yes
1                            No
2                           Yes
3                           Yes
4                            No
...                         ...
9995                        Yes
9996                        Yes
9997                        Yes
9998                        Yes
9999                         No

[10000 rows x 1 columns]

In [59]:
le=LabelEncoder()

In [60]:
le

LabelEncoder()

In [61]:
std["Extracurricular Activities"]=le.fit_transform(std)

/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [62]:
std

Extracurricular Activities
0                              1
1                              0
2                              1
3                              1
4                              0
...                          ...
9995                           1
9996                           1
9997                           1
9998                           1
9999                           0

[10000 rows x 1 columns]

In [63]:
cd=pd.concat(objs=[stu,std],axis=1)

In [64]:
cd

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0                 7               99                         Yes            9   
1                 4               82                          No            4   
2                 8               51                         Yes            7   
3                 5               52                         Yes            5   
4                 7               75                          No            8   
...             ...              ...                         ...          ...   
9995              1               49                         Yes            4   
9996              7               64                         Yes            8   
9997              6               83                         Yes            8   
9998              9               97                         Yes            7   
9999              7               74                          No            8   

      Sample Question Papers Practiced  Performance Index  \
0                                    1               91.0   
1                                    2               65.0   
2                                    2               45.0   
3                                    2               36.0   
4                                    5               66.0   
...                                ...                ...   
9995                                 2               23.0   
9996                                 5               58.0   
9997                                 5               74.0   
9998                                 0               95.0   
9999                                 1               64.0   

      Extracurricular Activities  
0                              1  
1                              0  
2                              1  
3                              1  
4                              0  
...                          ...  
9995                           1  
9996                           1  
9997                           1  
9998                           1  
9999                           0  

[10000 rows x 7 columns]

In [65]:
stu

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [66]:
le=LabelEncoder()
encode=le.fit_transform(stu['Extracurricular Activities'])

In [67]:
encode

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

In [68]:
stu["ECA"]=encode

In [69]:
stu

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  ECA  
0                                    1               91.0    1  
1                                    2               65.0    0  
2                                    2               45.0    1  
3                                    2               36.0    1  
4                                    5               66.0    0  
...                                ...                ...  ...  
9995                                 2               23.0    1  
9996                                 5               58.0    1  
9997                                 5               74.0    1  
9998                                 0               95.0    1  
9999                                 1               64.0    0  

[10000 rows x 7 columns]

In [70]:
stu.drop("Extracurricular Activities",axis=1,inplace=True)

In [71]:
stu

Hours Studied  Previous Scores  Sleep Hours  \
0                 7               99            9   
1                 4               82            4   
2                 8               51            7   
3                 5               52            5   
4                 7               75            8   
...             ...              ...          ...   
9995              1               49            4   
9996              7               64            8   
9997              6               83            8   
9998              9               97            7   
9999              7               74            8   

      Sample Question Papers Practiced  Performance Index  ECA  
0                                    1               91.0    1  
1                                    2               65.0    0  
2                                    2               45.0    1  
3                                    2               36.0    1  
4                                    5               66.0    0  
...                                ...                ...  ...  
9995                                 2               23.0    1  
9996                                 5               58.0    1  
9997                                 5               74.0    1  
9998                                 0               95.0    1  
9999                                 1               64.0    0  

[10000 rows x 6 columns]

In [72]:
y=stu["Performance Index"]

In [73]:
y

0       91.0
1       65.0
2       45.0
3       36.0
4       66.0
        ... 
9995    23.0
9996    58.0
9997    74.0
9998    95.0
9999    64.0
Name: Performance Index, Length: 10000, dtype: float64

In [74]:
pd.DataFrame(y)

Performance Index
0                  91.0
1                  65.0
2                  45.0
3                  36.0
4                  66.0
...                 ...
9995               23.0
9996               58.0
9997               74.0
9998               95.0
9999               64.0

[10000 rows x 1 columns]

In [75]:
X=stu.drop(["Performance Index"],axis=1)

In [76]:
X

Hours Studied  Previous Scores  Sleep Hours  \
0                 7               99            9   
1                 4               82            4   
2                 8               51            7   
3                 5               52            5   
4                 7               75            8   
...             ...              ...          ...   
9995              1               49            4   
9996              7               64            8   
9997              6               83            8   
9998              9               97            7   
9999              7               74            8   

      Sample Question Papers Practiced  ECA  
0                                    1    1  
1                                    2    0  
2                                    2    1  
3                                    2    1  
4                                    5    0  
...                                ...  ...  
9995                                 2    1  
9996                                 5    1  
9997                                 5    1  
9998                                 0    1  
9999                                 1    0  

[10000 rows x 5 columns]

In [77]:
from sklearn.preprocessing import StandardScaler

In [78]:
scaler=StandardScaler()

In [79]:
scaler

StandardScaler()

In [102]:
Xscaled=scaler.fit_transform(X)
scaler

StandardScaler()

In [81]:
Xscaled

array([[ 0.77518771,  1.70417565,  1.45620461, -1.24975394,  1.01045465],
       [-0.38348058,  0.72391268, -1.49229423, -0.90098215, -0.98965352],
       [ 1.16141048, -1.06362569,  0.27680507, -0.90098215,  1.01045465],
       ...,
       [ 0.38896495,  0.7815752 ,  0.86650484,  0.1453332 ,  1.01045465],
       [ 1.54763324,  1.5888506 ,  0.27680507, -1.59852572,  1.01045465],
       [ 0.77518771,  0.26261245,  0.86650484, -1.24975394, -0.98965352]],
      shape=(10000, 5))

In [82]:
from sklearn.model_selection import train_test_split

In [83]:
Xtrain,Xtest,ytrain,ytest=train_test_split(Xscaled,y,test_size=.3,random_state=3)

In [84]:
stu.size

60000

In [85]:
stu.shape

(10000, 6)

In [86]:
Xtrain.shape

(7000, 5)

In [87]:
Xtest.shape


(3000, 5)

In [88]:
from sklearn.linear_model import LinearRegression

In [89]:
modell=LinearRegression()

In [90]:
modell

LinearRegression()

In [91]:
modell.fit(Xtrain,ytrain)

LinearRegression()

In [92]:
modell.coef_

array([ 7.41290885, 17.67146829,  0.8109916 ,  0.5584829 ,  0.28889048])

In [93]:
modell.intercept_

np.float64(55.23702552811911)

In [94]:
predict=modell.predict(Xtest)

In [95]:
predict

array([74.85269888, 61.56058441, 15.09660608, ..., 20.66409091,
       21.2737445 , 74.44087491], shape=(3000,))

In [96]:
residual=ytest-predict

In [97]:
residual

5876   -1.852699
6555    1.439416
1448   -1.096606
3351    0.054020
231    -1.791465
          ...   
749    -0.693669
5373   -0.053535
485    -0.664091
5657    1.726256
676    -0.440875
Name: Performance Index, Length: 3000, dtype: float64

In [98]:
import joblib 

In [99]:
joblib.dump(modell,"LinearRegression.pkl")

['LinearRegression.pkl']

In [101]:
joblib.dump(le,"encoder.pkl")

['encoder.pkl']

In [103]:
joblib.dump(scaler,"Scaler.pkl")

['Scaler.pkl']